---

- hosts: all
  become: true
  tasks: 

  - name: install apache and php
    package:
      name:
        - "{{ apachePkg }}"
        - "{{ phpPkg }}"
      state: latest
      cache_valid_time: 50
    # when: ansible_distribution == "Ubuntu"



