---

- hosts: all
  become: true
  pre_tasks:

  - name: install udpates (Amazon Linux)
    yum:
      update_only: yes
      update_cache: yes
      cache_valid_time: 50
    when: ansible_distribution == "Amazon Linux"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      cache_valid_time: 50
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php in amazon linux
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package(centOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "centOS"


  - name: install mariadb package(Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest



