---

- hosts: all
  become: true
  pre_tasks:

  - name: install udpates (Amazon Linux)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
      cache_valid_time: 50
    when: ansible_distribution == "Amazon Linux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      cache_valid_time: 50
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    tags: apache, apache2, Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php in amazon linux
    tags: apache, centOS, httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package(centOS)
    tags: centOS, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "centOS"


  - name: install mariadb package(Ubuntu)
    tags: db, mariadb, Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    ansible.builtin.package:
      name: samba
      state: latest



