---

- hosts: all
  become: true
  pre_tasks:

  - name: install udpates (Amazon Linux)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
      cache_valid_time: 50
    when: ansible_distribution == "centOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      cache_valid_time: 50
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key form simone
    tags:  always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJVeVpc5sXAscLhwLQdNF01/JuWrGgvcPjyeCuMPHQu sharathwelcomesyouin@gmail.com"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoers_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terrraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    tags: apache, apache2, Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php in amazon linux
    tags: apache, centOS, httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start httpd (centOS)
    tags: apache, centOS, httpd
    service:
      name: httpd
      enabled: yes
      state: started
    when: ansible_distribution == "centOS"

  - name: change email address for admin
    tags: apache, centOS, httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "centOS"
    register: httpd

  - name: restart httpd (centOS)
    tags: apache, centOS, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package(centOS)
    tags: centOS, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "centOS"


  - name: install mariadb package(Ubuntu)
    tags: db, mariadb, Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    ansible.builtin.package:
      name: samba
      state: latest



