- name: install apache and php for Ubuntu
  tags: apache, apache2, Ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php in amazon linux
  tags: apache, centOS, httpd
  yum:
    name:
      - "{{ apache_service }}"
      - php
    state: latest
  when: ansible_distribution == "Amazon"

- name: start httpd (centOS)
  tags: apache, centOS, httpd
  service:
    name: "{{ apache_service }}"
    enabled: yes
    state: started
  when: ansible_distribution == "centOS"

- name: change email address for admin
  tags: apache, centOS, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "centOS"
  register: restart_apache


- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
